# Generated by Django 2.0.13 on 2019-07-13 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentprofile',
            unique_together={('teacher', 'class_id')},
        ),
    ]
