# Generated by Django 2.0.13 on 2019-08-01 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class_id',
            name='name',
            field=models.CharField(default='My Class', max_length=100),
        ),
    ]
