# Generated by Django 2.0.13 on 2019-08-01 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190801_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class_id',
            name='name',
            field=models.CharField(default='class_name', max_length=100),
        ),
    ]
