# Generated by Django 2.0.13 on 2019-07-13 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190713_2258'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentprofile',
            unique_together=set(),
        ),
    ]
