# Generated by Django 2.0.13 on 2019-08-10 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom_users', '0001_initial'),
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remainingexam',
            name='exam',
        ),
        migrations.RemoveField(
            model_name='remainingexam',
            name='user',
        ),
        migrations.AddField(
            model_name='completedexam',
            name='level',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='completedexam',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.Exam'),
        ),
        migrations.RemoveField(
            model_name='completedexam',
            name='user',
        ),
        migrations.AddField(
            model_name='completedexam',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='custom_users.StudentProfile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custom_users.StudentProfile'),
        ),
        migrations.DeleteModel(
            name='RemainingExam',
        ),
    ]
