# Generated by Django 2.0.13 on 2019-08-15 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_auto_20190815_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='correct_answer_to_display',
            field=models.BooleanField(default=False),
        ),
    ]
