# Generated by Django 2.0.13 on 2019-08-14 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_users', '0003_auto_20190814_0812'),
        ('exams', '0002_auto_20190812_1418'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='useranswer',
            unique_together={('user', 'question')},
        ),
    ]
