# Generated by Django 2.0.13 on 2019-07-31 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_auto_20190731_0816'),
    ]

    operations = [
        migrations.CreateModel(
            name='Written_Quesion',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='exams.Question')),
                ('is_written', models.BooleanField(default=True)),
            ],
            bases=('exams.question',),
        ),
    ]
