# Generated by Django 2.0.13 on 2019-09-05 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_question_questionimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='questionimage',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
