# Generated by Django 2.0.13 on 2019-07-31 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_written_quesion'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Written_Quesion',
            new_name='Written_Question',
        ),
    ]
