# Generated by Django 2.0.13 on 2019-08-15 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_answer_correct_answer_to_display'),
    ]

    operations = [
        migrations.AddField(
            model_name='completedexam',
            name='title',
            field=models.CharField(default="An Exam's Title", max_length=1000),
        ),
    ]
