# Generated by Django 2.0.13 on 2019-07-28 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_auto_20190727_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_MCQ',
            field=models.BooleanField(default=True),
        ),
    ]
