# Generated by Django 2.0.13 on 2019-08-14 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_users', '0003_auto_20190814_0812'),
        ('exams', '0003_auto_20190814_0812'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='completedexam',
            unique_together={('user', 'exam', 'level')},
        ),
    ]
