# Generated by Django 2.0.13 on 2019-07-31 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_auto_20190731_0821'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formula_question',
            options={'verbose_name': 'Formula_Question'},
        ),
        migrations.AlterModelOptions(
            name='mcq_question',
            options={'verbose_name': 'MCQ_Question'},
        ),
        migrations.AlterModelOptions(
            name='written_question',
            options={'verbose_name': 'Written_Question'},
        ),
        migrations.RemoveField(
            model_name='answer',
            name='is_formula',
        ),
    ]
