# Generated by Django 2.0.13 on 2019-08-14 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_users', '0003_auto_20190814_0812'),
        ('exams', '0004_auto_20190814_0820'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='useranswer',
            unique_together={('user', 'question', 'user_answer')},
        ),
    ]
