# Generated by Django 2.0.13 on 2019-07-28 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_question_is_mcq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranswer',
            name='user_answer',
            field=models.CharField(max_length=1000),
        ),
    ]
