# Generated by Django 2.0.13 on 2019-08-16 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_completedexam_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='completedexam',
            name='title',
        ),
    ]
