# Generated by Django 2.0.13 on 2019-07-28 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0005_auto_20190728_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswer',
            name='correct_spelling',
            field=models.BooleanField(default=True),
        ),
    ]
