# Generated by Django 2.0.13 on 2019-09-12 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0005_auto_20190912_0859'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='questionreview',
            new_name='questionreviewimage',
        ),
    ]
