# Generated by Django 2.0.13 on 2019-07-28 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0006_useranswer_correct_spelling'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useranswer',
            name='correct_spelling',
        ),
        migrations.AddField(
            model_name='answer',
            name='correct_spelling',
            field=models.BooleanField(default=True),
        ),
    ]
