# Generated by Django 2.0.13 on 2019-08-14 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0006_auto_20190814_1451'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='completedexam',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='useranswer',
            unique_together=set(),
        ),
    ]
