# Generated by Django 2.0.13 on 2019-09-13 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0006_auto_20190912_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='questiongif',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
