# Generated by Django 2.0.13 on 2019-07-29 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0007_auto_20190728_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_formula',
            field=models.BooleanField(default=False),
        ),
    ]
