# Generated by Django 2.0.13 on 2019-08-10 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
        ('custom_users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='completed_lessons',
            field=models.ManyToManyField(to='lessons.Lesson'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='next_lesson_id',
            field=models.IntegerField(default=1),
        ),
    ]
