# Generated by Django 2.0.13 on 2019-08-12 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='next_exam_id',
            field=models.IntegerField(default=1),
        ),
    ]
