# Generated by Django 2.0.13 on 2019-08-15 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='needs_help',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='progress',
            field=models.IntegerField(default=1),
        ),
    ]
