# Generated by Django 2.0.13 on 2019-08-14 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_users', '0002_studentprofile_next_exam_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class_id',
            name='name',
            field=models.CharField(default='My Class', max_length=100, unique=True),
        ),
    ]
