# Generated by Django 2.0.13 on 2019-08-10 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_users', '0002_auto_20190810_1349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='next_lesson_id',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='next_lesson_name',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
