# Generated by Django 2.0.13 on 2019-08-15 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_users', '0003_studentprofile_starting_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='progress',
            field=models.IntegerField(default=1000),
        ),
    ]
