# Generated by Django 2.0.13 on 2019-08-22 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_users', '0004_auto_20190815_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='progress',
            field=models.IntegerField(default=2),
        ),
    ]
