# Generated by Django 2.0.13 on 2019-08-22 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_users', '0005_auto_20190822_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class_id',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
