# Generated by Django 2.0.13 on 2019-08-10 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='number',
        ),
    ]
