# Generated by Django 2.0.13 on 2019-08-10 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_auto_20190810_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='image_link',
            field=models.CharField(default='lesson_image_link', max_length=500),
        ),
    ]
